/**
 * systemConfig.js - My Simulator
 * 
 * Generated by Process Simulator Designer v2.0.0
 * Export Date: 10/14/2025, 4:22:03 PM
 * 
 * ⚠️ IMPORTANT PATH REQUIREMENTS:
 * This file expects the following structure:
 *   sims/my-simulator/
 *   ├── index.html
 *   ├── systemConfig.js (this file)
 *   └── README.md
 *   
 *   engine/ (at ../../engine/ from this file)
 *   ├── core/
 *   ├── components/
 *   └── managers/
 *   
 *   valve.html (at ../../valve.html from this file)
 */

const SYSTEM_CONFIG = {
  "_metadata": {
    "name": "My Simulator",
    "version": "1.0.0",
    "exportVersion": "2.0.0",
    "designerVersion": "2.0.0",
    "exported": "2025-10-14T21:22:03.271Z",
    "componentCount": 11,
    "connectionCount": 10
  },
  "feeds": {
    "comp_1": {
      "id": "comp_1",
      "name": "Feed 2",
      "type": "feed",
      "supplyPressure": 3,
      "maxFlow": null,
      "temperature": 20,
      "inputs": [],
      "outputs": [
        "comp_5"
      ],
      "position": [
        80,
        200
      ]
    },
    "comp_2": {
      "id": "comp_2",
      "name": "Feed 3",
      "type": "feed",
      "supplyPressure": 3,
      "maxFlow": null,
      "temperature": 20,
      "inputs": [],
      "outputs": [
        "comp_4"
      ],
      "position": [
        80,
        320
      ]
    },
    "comp_9": {
      "id": "comp_9",
      "name": "Feed 10",
      "type": "feed",
      "supplyPressure": 3,
      "maxFlow": null,
      "temperature": 20,
      "inputs": [],
      "outputs": [
        "comp_10"
      ],
      "position": [
        660,
        0
      ]
    }
  },
  "drains": {
    "comp_11": {
      "id": "comp_11",
      "name": "Drain 12",
      "type": "drain",
      "ambientPressure": 1,
      "maxCapacity": null,
      "inputs": [
        "comp_8"
      ],
      "outputs": [],
      "position": [
        940,
        280
      ]
    }
  },
  "tanks": {
    "comp_3": {
      "id": "comp_3",
      "name": "Tank 4",
      "type": "tank",
      "area": 2.5,
      "maxHeight": 1.2,
      "initialVolume": 0,
      "inputs": [
        "comp_5",
        "comp_4"
      ],
      "outputs": [
        "comp_6"
      ],
      "svgElement": "#comp_3",
      "position": [
        360,
        240
      ]
    },
    "comp_8": {
      "id": "comp_8",
      "name": "Tank 9",
      "type": "tank",
      "area": 2.5,
      "maxHeight": 1.2,
      "initialVolume": 0,
      "inputs": [
        "comp_7",
        "comp_10"
      ],
      "outputs": [
        "comp_11"
      ],
      "svgElement": "#comp_8",
      "position": [
        800,
        240
      ]
    }
  },
  "pumps": {
    "comp_6": {
      "id": "comp_6",
      "name": "Fixed Speed Pump 7",
      "type": "pump",
      "pumpType": "fixed",
      "capacity": 0.5,
      "efficiency": 0.95,
      "inputs": [
        "comp_3"
      ],
      "outputs": [
        "comp_7"
      ],
      "svgElement": "#comp_6",
      "position": [
        580,
        280
      ],
      "modalTitle": "Fixed Speed Pump 7 Control"
    }
  },
  "valves": {
    "comp_4": {
      "id": "comp_4",
      "name": "Control Valve 5",
      "type": "valve",
      "maxFlow": 0.5,
      "initialPosition": 0,
      "responseTime": 0.1,
      "inputs": [
        "comp_2"
      ],
      "outputs": [
        "comp_3"
      ],
      "svgElement": "#comp_4",
      "position": [
        180,
        320
      ],
      "iframeUrl": "../../valve.html",
      "modalTitle": "Control Valve 5 Control"
    },
    "comp_5": {
      "id": "comp_5",
      "name": "Control Valve 6",
      "type": "valve",
      "maxFlow": 0.5,
      "initialPosition": 0,
      "responseTime": 0.1,
      "inputs": [
        "comp_1"
      ],
      "outputs": [
        "comp_3"
      ],
      "svgElement": "#comp_5",
      "position": [
        180,
        200
      ],
      "iframeUrl": "../../valve.html",
      "modalTitle": "Control Valve 6 Control"
    },
    "comp_7": {
      "id": "comp_7",
      "name": "Control Valve 8",
      "type": "valve",
      "maxFlow": 0.5,
      "initialPosition": 0,
      "responseTime": 0.1,
      "inputs": [
        "comp_6"
      ],
      "outputs": [
        "comp_8"
      ],
      "svgElement": "#comp_7",
      "position": [
        560,
        140
      ],
      "iframeUrl": "../../valve.html",
      "modalTitle": "Control Valve 8 Control"
    },
    "comp_10": {
      "id": "comp_10",
      "name": "Control Valve 11",
      "type": "valve",
      "maxFlow": 0.5,
      "initialPosition": 0,
      "responseTime": 0.1,
      "inputs": [
        "comp_9"
      ],
      "outputs": [
        "comp_8"
      ],
      "svgElement": "#comp_10",
      "position": [
        780,
        0
      ],
      "iframeUrl": "../../valve.html",
      "modalTitle": "Control Valve 11 Control"
    }
  },
  "pipes": {
    "pipe1": {
      "id": "pipe1",
      "name": "Feed 2 to Control Valve 6",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.1,
      "svgElement": "#pipe1Flow",
      "inputs": [
        "comp_1"
      ],
      "outputs": [
        "comp_5"
      ]
    },
    "pipe2": {
      "id": "pipe2",
      "name": "Control Valve 6 to Tank 4",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.2,
      "svgElement": "#pipe2Flow",
      "inputs": [
        "comp_5"
      ],
      "outputs": [
        "comp_3"
      ]
    },
    "pipe3": {
      "id": "pipe3",
      "name": "Feed 3 to Control Valve 5",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.1,
      "svgElement": "#pipe3Flow",
      "inputs": [
        "comp_2"
      ],
      "outputs": [
        "comp_4"
      ]
    },
    "pipe4": {
      "id": "pipe4",
      "name": "Control Valve 5 to Tank 4",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.2,
      "svgElement": "#pipe4Flow",
      "inputs": [
        "comp_4"
      ],
      "outputs": [
        "comp_3"
      ]
    },
    "pipe5": {
      "id": "pipe5",
      "name": "Tank 4 to Fixed Speed Pump 7",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.2,
      "svgElement": "#pipe5Flow",
      "inputs": [
        "comp_3"
      ],
      "outputs": [
        "comp_6"
      ]
    },
    "pipe6": {
      "id": "pipe6",
      "name": "Fixed Speed Pump 7 to Control Valve 8",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.1,
      "svgElement": "#pipe6Flow",
      "inputs": [
        "comp_6"
      ],
      "outputs": [
        "comp_7"
      ]
    },
    "pipe7": {
      "id": "pipe7",
      "name": "Control Valve 8 to Tank 9",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.3,
      "svgElement": "#pipe7Flow",
      "inputs": [
        "comp_7"
      ],
      "outputs": [
        "comp_8"
      ]
    },
    "pipe8": {
      "id": "pipe8",
      "name": "Tank 9 to Drain 12",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.1,
      "svgElement": "#pipe8Flow",
      "inputs": [
        "comp_8"
      ],
      "outputs": [
        "comp_11"
      ]
    },
    "pipe9": {
      "id": "pipe9",
      "name": "Feed 10 to Control Valve 11",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.1,
      "svgElement": "#pipe9Flow",
      "inputs": [
        "comp_9"
      ],
      "outputs": [
        "comp_10"
      ]
    },
    "pipe10": {
      "id": "pipe10",
      "name": "Control Valve 11 to Tank 9",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.2,
      "svgElement": "#pipe10Flow",
      "inputs": [
        "comp_10"
      ],
      "outputs": [
        "comp_8"
      ]
    }
  },
  "pressureSensors": {},
  "settings": {
    "timeStep": 0.016,
    "maxTimeStep": 0.1,
    "gravity": 9.81,
    "fluidDensity": 1000,
    "updateInterval": 16,
    "debugMode": true,
    "logFlows": false
  }
};

// Validation
function validateConfig(config) {
  const errors = [];
  const allIds = new Set();
  
  for (const [category, items] of Object.entries(config)) {
    if (category === 'settings' || category === '_metadata') continue;
    for (const [key, item] of Object.entries(items)) {
      if (allIds.has(item.id)) {
        errors.push(`Duplicate ID: ${item.id}`);
      }
      allIds.add(item.id);
    }
  }
  
  if (errors.length > 0) {
    console.error('Configuration errors:', errors);
    return false;
  }
  
  console.log('✓ Configuration validated');
  return true;
}

// Version check
function checkEngineVersion() {
  const required = '1.0.0';
  const current = window.ENGINE_VERSION || 'unknown';
  
  if (current !== required && current !== 'unknown') {
    console.warn(`⚠️ Engine version mismatch: Config expects ${required}, found ${current}`);
  }
}

// Export
window.SYSTEM_CONFIG = SYSTEM_CONFIG;
window.validateConfig = validateConfig;

// Auto-validate
if (validateConfig(SYSTEM_CONFIG)) {
  checkEngineVersion();
  console.log('✅ System configuration loaded');
  console.log('📋 Components:', {
    feeds: Object.keys(SYSTEM_CONFIG.feeds).length,
    tanks: Object.keys(SYSTEM_CONFIG.tanks).length,
    pumps: Object.keys(SYSTEM_CONFIG.pumps).length,
    valves: Object.keys(SYSTEM_CONFIG.valves).length,
    drains: Object.keys(SYSTEM_CONFIG.drains).length,
    pipes: Object.keys(SYSTEM_CONFIG.pipes).length,
    sensors: Object.keys(SYSTEM_CONFIG.pressureSensors).length
  });
}