/**
 * systemConfig.js - My Simulator Configuration
 * Generated by Process Simulator Designer
 * 2025-10-14T00:07:29.058Z
 */

const SYSTEM_CONFIG = {
  "feeds": {
    "comp_2": {
      "id": "comp_2",
      "name": "Feed 3",
      "type": "feed",
      "supplyPressure": 3,
      "maxFlow": null,
      "temperature": 20,
      "inputs": [],
      "outputs": [
        "comp_6"
      ],
      "position": [
        140,
        260
      ]
    },
    "comp_3": {
      "id": "comp_3",
      "name": "Feed 4",
      "type": "feed",
      "supplyPressure": 3,
      "maxFlow": null,
      "temperature": 20,
      "inputs": [],
      "outputs": [
        "comp_5"
      ],
      "position": [
        140,
        160
      ]
    },
    "comp_7": {
      "id": "comp_7",
      "name": "Feed 8",
      "type": "feed",
      "supplyPressure": 3,
      "maxFlow": null,
      "temperature": 20,
      "inputs": [],
      "outputs": [
        "comp_8"
      ],
      "position": [
        740,
        60
      ]
    }
  },
  "drains": {
    "comp_10": {
      "id": "comp_10",
      "name": "Drain 11",
      "type": "drain",
      "ambientPressure": 1,
      "maxCapacity": null,
      "inputs": [
        "comp_11"
      ],
      "outputs": [],
      "position": [
        1140,
        260
      ]
    }
  },
  "tanks": {
    "comp_1": {
      "id": "comp_1",
      "name": "Tank 2",
      "type": "tank",
      "area": 2.5,
      "maxHeight": 1.2,
      "initialVolume": 0,
      "inputs": [
        "comp_5",
        "comp_6"
      ],
      "outputs": [
        "comp_4"
      ],
      "svgElement": "#comp_1",
      "position": [
        440,
        260
      ]
    },
    "comp_8": {
      "id": "comp_8",
      "name": "Tank 9",
      "type": "tank",
      "area": 2.5,
      "maxHeight": 1.2,
      "initialVolume": 0,
      "inputs": [
        "comp_4",
        "comp_7"
      ],
      "outputs": [
        "comp_9"
      ],
      "svgElement": "#comp_8",
      "position": [
        760,
        260
      ]
    }
  },
  "pumps": {
    "comp_4": {
      "id": "comp_4",
      "name": "Fixed Speed Pump 5",
      "type": "pump",
      "pumpType": "fixed",
      "capacity": 0.5,
      "efficiency": 0.95,
      "inputs": [
        "comp_1"
      ],
      "outputs": [
        "comp_8"
      ],
      "svgElement": "#comp_4",
      "position": [
        600,
        260
      ],
      "modalTitle": "Fixed Speed Pump 5 Control"
    },
    "comp_9": {
      "id": "comp_9",
      "name": "Variable Speed Pump 10",
      "type": "pump",
      "pumpType": "variable",
      "capacity": 0.5,
      "efficiency": 0.95,
      "minSpeed": 0.1,
      "inputs": [
        "comp_8"
      ],
      "outputs": [
        "comp_11"
      ],
      "svgElement": "#comp_9",
      "position": [
        920,
        260
      ],
      "modalTitle": "Variable Speed Pump 10 Control"
    }
  },
  "valves": {
    "comp_5": {
      "id": "comp_5",
      "name": "Control Valve 6",
      "type": "valve",
      "maxFlow": 0.5,
      "initialPosition": 0,
      "responseTime": 0.1,
      "inputs": [
        "comp_3"
      ],
      "outputs": [
        "comp_1"
      ],
      "svgElement": "#comp_5",
      "position": [
        280,
        160
      ],
      "iframeUrl": "../../valve.html",
      "modalTitle": "Control Valve 6 Control"
    },
    "comp_6": {
      "id": "comp_6",
      "name": "Control Valve 7",
      "type": "valve",
      "maxFlow": 0.5,
      "initialPosition": 0,
      "responseTime": 0.1,
      "inputs": [
        "comp_2"
      ],
      "outputs": [
        "comp_1"
      ],
      "svgElement": "#comp_6",
      "position": [
        280,
        260
      ],
      "iframeUrl": "../../valve.html",
      "modalTitle": "Control Valve 7 Control"
    },
    "comp_11": {
      "id": "comp_11",
      "name": "Control Valve 12",
      "type": "valve",
      "maxFlow": 0.5,
      "initialPosition": 0,
      "responseTime": 0.1,
      "inputs": [
        "comp_9"
      ],
      "outputs": [
        "comp_10"
      ],
      "svgElement": "#comp_11",
      "position": [
        1040,
        260
      ],
      "iframeUrl": "../../valve.html",
      "modalTitle": "Control Valve 12 Control"
    }
  },
  "pipes": {
    "pipe1": {
      "id": "pipe1",
      "name": "Feed 4 to Control Valve 6",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.1,
      "svgElement": "#pipe1Flow",
      "inputs": [
        "comp_3"
      ],
      "outputs": [
        "comp_5"
      ]
    },
    "pipe2": {
      "id": "pipe2",
      "name": "Control Valve 6 to Tank 2",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.2,
      "svgElement": "#pipe2Flow",
      "inputs": [
        "comp_5"
      ],
      "outputs": [
        "comp_1"
      ]
    },
    "pipe3": {
      "id": "pipe3",
      "name": "Feed 3 to Control Valve 7",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.1,
      "svgElement": "#pipe3Flow",
      "inputs": [
        "comp_2"
      ],
      "outputs": [
        "comp_6"
      ]
    },
    "pipe4": {
      "id": "pipe4",
      "name": "Control Valve 7 to Tank 2",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.2,
      "svgElement": "#pipe4Flow",
      "inputs": [
        "comp_6"
      ],
      "outputs": [
        "comp_1"
      ]
    },
    "pipe5": {
      "id": "pipe5",
      "name": "Tank 2 to Fixed Speed Pump 5",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.2,
      "svgElement": "#pipe5Flow",
      "inputs": [
        "comp_1"
      ],
      "outputs": [
        "comp_4"
      ]
    },
    "pipe6": {
      "id": "pipe6",
      "name": "Fixed Speed Pump 5 to Tank 9",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.2,
      "svgElement": "#pipe6Flow",
      "inputs": [
        "comp_4"
      ],
      "outputs": [
        "comp_8"
      ]
    },
    "pipe7": {
      "id": "pipe7",
      "name": "Feed 8 to Tank 9",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.2,
      "svgElement": "#pipe7Flow",
      "inputs": [
        "comp_7"
      ],
      "outputs": [
        "comp_8"
      ]
    },
    "pipe8": {
      "id": "pipe8",
      "name": "Tank 9 to Variable Speed Pump 10",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.2,
      "svgElement": "#pipe8Flow",
      "inputs": [
        "comp_8"
      ],
      "outputs": [
        "comp_9"
      ]
    },
    "pipe9": {
      "id": "pipe9",
      "name": "Variable Speed Pump 10 to Control Valve 12",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.1,
      "svgElement": "#pipe9Flow",
      "inputs": [
        "comp_9"
      ],
      "outputs": [
        "comp_11"
      ]
    },
    "pipe10": {
      "id": "pipe10",
      "name": "Control Valve 12 to Drain 11",
      "type": "pipe",
      "diameter": 0.05,
      "length": 0.1,
      "svgElement": "#pipe10Flow",
      "inputs": [
        "comp_11"
      ],
      "outputs": [
        "comp_10"
      ]
    }
  },
  "pressureSensors": {},
  "settings": {
    "timeStep": 0.016,
    "maxTimeStep": 0.1,
    "gravity": 9.81,
    "fluidDensity": 1000,
    "updateInterval": 16,
    "debugMode": true,
    "logFlows": false
  }
};

// Validation
function validateConfig(config) {
  const errors = [];
  const allIds = new Set();
  
  for (const [category, items] of Object.entries(config)) {
    if (category === 'settings') continue;
    for (const [key, item] of Object.entries(items)) {
      if (allIds.has(item.id)) {
        errors.push(`Duplicate ID: ${item.id}`);
      }
      allIds.add(item.id);
    }
  }
  
  if (errors.length > 0) {
    console.error('Configuration errors:', errors);
    return false;
  }
  
  console.log('✓ Configuration validated successfully');
  return true;
}

// Export
window.SYSTEM_CONFIG = SYSTEM_CONFIG;
window.validateConfig = validateConfig;

// Auto-validate
if (validateConfig(SYSTEM_CONFIG)) {
  console.log('✅ System configuration loaded');
  console.log('📋 Components:', {
    feeds: Object.keys(SYSTEM_CONFIG.feeds).length,
    tanks: Object.keys(SYSTEM_CONFIG.tanks).length,
    pumps: Object.keys(SYSTEM_CONFIG.pumps).length,
    valves: Object.keys(SYSTEM_CONFIG.valves).length,
    drains: Object.keys(SYSTEM_CONFIG.drains).length,
    pipes: Object.keys(SYSTEM_CONFIG.pipes).length,
    sensors: Object.keys(SYSTEM_CONFIG.pressureSensors).length
  });
}