/**
 * exporter.js - Export designer to working simulator files
 */

class SimulatorExporter {
  constructor(designer) {
    this.designer = designer;
  }

  /**
   * Export complete simulator
   */
  async exportSimulator(simName = 'my-sim') {
    // Clean sim name for filenames
    const cleanName = simName.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    
    // Generate files
    const files = {
      'systemConfig.js': this.generateSystemConfig(simName),
      'index.html': this.generateIndexHTML(simName),
      'README.md': this.generateReadme(simName, cleanName)
    };
    
    // Download as zip or individual files
    this.downloadFiles(files, cleanName);
    
    console.log(`✅ Exported simulator: ${simName}`);
  }

  /**
   * Generate systemConfig.js
   */
  generateSystemConfig(simName) {
    const components = Array.from(this.designer.components.values());
    const connections = this.designer.connections;
    
    // Group components by type
    const grouped = {
      feeds: {},
      drains: {},
      tanks: {},
      pumps: {},
      valves: {},
      pipes: {},
      pressureSensors: {}
    };
    
    // Process each component
    components.forEach(comp => {
      const cleanId = this._cleanId(comp.id);
      const config = this._buildComponentConfig(comp, cleanId);
      
      // Route to correct category
      if (comp.type === 'feed') {
        grouped.feeds[cleanId] = config;
      } else if (comp.type === 'drain') {
        grouped.drains[cleanId] = config;
      } else if (comp.type === 'tank') {
        grouped.tanks[cleanId] = config;
      } else if (comp.type === 'pump') {
        grouped.pumps[cleanId] = config;
      } else if (comp.type === 'valve') {
        grouped.valves[cleanId] = config;
      } else if (comp.type === 'sensor') {
        grouped.pressureSensors[cleanId] = config;
      }
    });
    
    // Generate pipes from connections
    connections.forEach((conn, idx) => {
      const fromComp = this.designer.components.get(conn.from);
      const toComp = this.designer.components.get(conn.to);
      const pipeId = `pipe${idx + 1}`;
      
      grouped.pipes[pipeId] = {
        id: pipeId,
        name: `${fromComp.name} to ${toComp.name}`,
        type: 'pipe',
        diameter: 0.05,
        length: this._calculateDistance(fromComp, toComp),
        svgElement: `#${pipeId}Flow`,
        inputs: [this._cleanId(conn.from)],
        outputs: [this._cleanId(conn.to)]
      };
    });
    
    // Build complete config
    const configJS = `/**
 * systemConfig.js - ${simName} Configuration
 * Generated by Process Simulator Designer
 * ${new Date().toISOString()}
 */

const SYSTEM_CONFIG = ${JSON.stringify({
      feeds: grouped.feeds,
      drains: grouped.drains,
      tanks: grouped.tanks,
      pumps: grouped.pumps,
      valves: grouped.valves,
      pipes: grouped.pipes,
      pressureSensors: grouped.pressureSensors,
      settings: {
        timeStep: 0.016,
        maxTimeStep: 0.1,
        gravity: 9.81,
        fluidDensity: 1000,
        updateInterval: 16,
        debugMode: true,
        logFlows: false
      }
    }, null, 2)};

// Validation
function validateConfig(config) {
  const errors = [];
  const allIds = new Set();
  
  for (const [category, items] of Object.entries(config)) {
    if (category === 'settings') continue;
    for (const [key, item] of Object.entries(items)) {
      if (allIds.has(item.id)) {
        errors.push(\`Duplicate ID: \${item.id}\`);
      }
      allIds.add(item.id);
    }
  }
  
  if (errors.length > 0) {
    console.error('Configuration errors:', errors);
    return false;
  }
  
  console.log('✓ Configuration validated successfully');
  return true;
}

// Export
window.SYSTEM_CONFIG = SYSTEM_CONFIG;
window.validateConfig = validateConfig;

// Auto-validate
if (validateConfig(SYSTEM_CONFIG)) {
  console.log('✅ System configuration loaded');
  console.log('📋 Components:', {
    feeds: Object.keys(SYSTEM_CONFIG.feeds).length,
    tanks: Object.keys(SYSTEM_CONFIG.tanks).length,
    pumps: Object.keys(SYSTEM_CONFIG.pumps).length,
    valves: Object.keys(SYSTEM_CONFIG.valves).length,
    drains: Object.keys(SYSTEM_CONFIG.drains).length,
    pipes: Object.keys(SYSTEM_CONFIG.pipes).length,
    sensors: Object.keys(SYSTEM_CONFIG.pressureSensors).length
  });
}`;
    
    return configJS;
  }

  /**
   * Generate index.html
   */
  generateIndexHTML(simName) {
    const components = Array.from(this.designer.components.values());
    const connections = this.designer.connections;
    
    // Generate SVG for each component
    const componentsSVG = components.map(comp => this._generateComponentSVG(comp)).join('\n        ');
    
    // Generate pipes
    const pipesSVG = connections.map((conn, idx) => this._generatePipeSVG(conn, idx)).join('\n        ');
    
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <title>${simName} - Process Simulator</title>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <link rel="stylesheet" href="../../engine/style.css">

  <!-- Core Architecture -->
  <script src="../../engine/core/Component.js" defer></script>
  <script src="../../engine/core/FlowNetwork.js" defer></script>
  <script src="../../engine/core/ComponentManager.js" defer></script>

  <!-- Boundary Components -->
  <script src="../../engine/components/sources/Feed.js" defer></script>
  <script src="../../engine/components/sinks/Drain.js" defer></script>

  <!-- Tank Components -->
  <script src="../../engine/components/tanks/Tank.js" defer></script>

  <!-- Pump Components -->
  <script src="../../engine/components/pumps/Pump.js" defer></script>
  <script src="../../engine/components/pumps/FixedSpeedPump.js" defer></script>
  <script src="../../engine/components/pumps/VariableSpeedPump.js" defer></script>
  <script src="../../engine/components/pumps/ThreeSpeedPump.js" defer></script>

  <!-- Valve Components -->
  <script src="../../engine/components/valves/Valve.js" defer></script>

  <!-- Pipe Components -->
  <script src="../../engine/components/pipes/Pipe.js" defer></script>

  <!-- Sensor Components -->
  <script src="../../engine/components/sensors/PressureSensor.js" defer></script>

  <!-- Managers -->
  <script src="../../engine/managers/TankManager.js" defer></script>
  <script src="../../engine/managers/PumpManager.js" defer></script>
  <script src="../../engine/managers/ValveManager.js" defer></script>
  <script src="../../engine/managers/PipeManager.js" defer></script>
  <script src="../../engine/managers/PressureManager.js" defer></script>

  <!-- Configuration -->
  <script src="./systemConfig.js" defer></script>

  <!-- Initialize System -->
  <script defer>
    window.addEventListener('DOMContentLoaded', () => {
      setTimeout(() => {
        console.log('=== INITIALIZING SYSTEM ===');
        
        if (!window.SYSTEM_CONFIG) {
          console.error('❌ SYSTEM_CONFIG not loaded');
          return;
        }
        if (!window.ComponentManager) {
          console.error('❌ ComponentManager not loaded');
          return;
        }
        
        console.log('✅ All components loaded');
        
        window.componentManager = new ComponentManager(SYSTEM_CONFIG);
        window.componentManager.initialize().then(success => {
          if (success) {
            console.log('✅ System initialized successfully');
            window.componentManager.start();
            console.log('✅ Simulation started');
          } else {
            console.error('❌ System initialization failed');
          }
        });
      }, 500);
    });
  </script>
</head>

<body>

<button id="controlsToggle" class="controls-toggle" aria-controls="controlsDrawer" aria-expanded="false">
  Controls
</button>
  
<div class="app">
  <div class="grid">
    <div class="card stage">
      <svg viewBox="0 0 ${this.designer.canvas.viewBox.baseVal.width} ${this.designer.canvas.viewBox.baseVal.height}" aria-labelledby="title desc" role="img">
        <title id="title">${simName}</title>
        <desc id="desc">Interactive process simulator. Click components to control them.</desc>
        
        <defs>
          <pattern id="grid" width="${this.designer.gridSize || 20}" height="${this.designer.gridSize || 20}" patternUnits="userSpaceOnUse">
            <path d="M ${this.designer.gridSize || 20} 0 L 0 0 0 ${this.designer.gridSize || 20}" fill="none" stroke="#22305f" stroke-width="1"></path>
          </pattern>
          <linearGradient id="liquid" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stop-color="#7cc8ff"></stop>
            <stop offset="100%" stop-color="#2d8bd6"></stop>
          </linearGradient>
        </defs>
        
        <rect x="0" y="0" width="${this.designer.canvas.viewBox.baseVal.width}" height="${this.designer.canvas.viewBox.baseVal.height}" fill="url(#grid)" opacity="0.4"></rect>
        
        <!-- PIPES (Background Layer) -->
        ${pipesSVG}
        
        <!-- COMPONENTS (Foreground Layer) -->
        ${componentsSVG}
      </svg>
    </div>

    <!-- Controls Drawer -->
    <aside id="controlsDrawer" class="controls-drawer" aria-hidden="true">
      <div class="controls-panel card" role="dialog" aria-modal="true" aria-labelledby="controlsTitle">
        <button id="controlsClose" class="controls-close" aria-label="Close controls">×</button>

        <div>
          <h1 id="controlsTitle">System Controls</h1>
          <div class="sub">${simName} - Click components to interact</div>
          
          <div class="controls">
            <div class="row">
              <button type="button" id="pauseBtn" aria-pressed="false" class="btn">Pause</button>
              <button type="button" id="resetBtn" class="btn">Reset</button>
            </div>
          </div>

          <hr/>
          <h1>System Status</h1>
          <div class="kv" id="systemStatus">
            <div>Status</div><div id="simStatus">Running</div>
          </div>
          
          <hr/>
          <h1>Debug</h1>
          <button type="button" id="debugBtn" class="btn">Show Debug Info</button>
          <pre id="debugOutput" style="display:none; font-size:10px; max-height:200px; overflow:auto; background:#0e1734; padding:8px; margin-top:8px;"></pre>
        </div>
      </div>
    </aside>
  </div>
</div>

<!-- Controls Drawer Script -->
<script>
(function(){
  const drawer = document.getElementById('controlsDrawer');
  const panel = drawer.querySelector('.controls-panel');
  const toggle = document.getElementById('controlsToggle');
  const closeBtn = document.getElementById('controlsClose');

  function openDrawer(){
    drawer.classList.add('open');
    drawer.setAttribute('aria-hidden','false');
    toggle.setAttribute('aria-expanded','true');
    setTimeout(() => closeBtn.focus(), 0);
  }
  function closeDrawer(){
    drawer.classList.remove('open');
    drawer.setAttribute('aria-hidden','true');
    toggle.setAttribute('aria-expanded','false');
    toggle.focus();
  }

  toggle.addEventListener('click', openDrawer);
  closeBtn.addEventListener('click', closeDrawer);
  drawer.addEventListener('click', (e) => {
    if (!panel.contains(e.target)) closeDrawer();
  });
  window.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && drawer.classList.contains('open')) closeDrawer();
  });
  
  // Pause button
  const pauseBtn = document.getElementById('pauseBtn');
  pauseBtn?.addEventListener('click', () => {
    if (window.componentManager) {
      if (window.componentManager.paused) {
        window.componentManager.resume();
        pauseBtn.textContent = 'Pause';
      } else {
        window.componentManager.pause();
        pauseBtn.textContent = 'Resume';
      }
    }
  });
  
  // Reset button
  const resetBtn = document.getElementById('resetBtn');
  resetBtn?.addEventListener('click', () => {
    if (window.componentManager) {
      window.componentManager.reset();
      console.log('System reset');
    }
  });
  
  // Debug button
  const debugBtn = document.getElementById('debugBtn');
  const debugOutput = document.getElementById('debugOutput');
  debugBtn?.addEventListener('click', () => {
    if (window.componentManager) {
      const info = window.componentManager.getSystemInfo();
      debugOutput.textContent = JSON.stringify(info, null, 2);
      debugOutput.style.display = debugOutput.style.display === 'none' ? 'block' : 'none';
    }
  });
})();
</script>

</body>
</html>`;
    
    return html;
  }

  /**
   * Generate README.md
   */
  generateReadme(simName, cleanName) {
    const components = Array.from(this.designer.components.values());
    
    return `# ${simName}

Generated by Process Simulator Designer  
Date: ${new Date().toLocaleDateString()}

## Components

${components.map(comp => `- **${comp.name}** (${comp.type})`).join('\n')}

## Setup

1. Place this folder in \`sims/${cleanName}/\`
2. Ensure the \`engine/\` folder exists at \`../../engine/\`
3. Open \`index.html\` in a web browser

## File Structure

\`\`\`
sims/${cleanName}/
├── index.html          # Simulator interface
├── systemConfig.js     # System configuration
└── README.md           # This file
\`\`\`

## Usage

1. Open \`index.html\` in your browser
2. Click **Controls** button to open control panel
3. Click components (pumps, valves) to interact with them
4. Watch the simulation run in real-time

## Controls

- **Pause/Resume**: Stop/start simulation
- **Reset**: Return all components to initial state
- **Debug**: View system state as JSON

## Notes

- All paths to engine files are relative (\`../../engine/\`)
- Requires modern browser with SVG and JavaScript support
- No server required - runs entirely in browser

---

Built with [Process Simulator Designer](https://github.com/yourusername/tank-sim)
`;
  }

  /**
   * Build component configuration
   */
  _buildComponentConfig(comp, cleanId) {
    const config = {
      id: cleanId,
      name: comp.name,
      type: comp.type,
      ...comp.config
    };
    
    // Add SVG element reference if visual component
    if (comp.type === 'valve' || comp.type === 'pump' || comp.type === 'tank') {
      config.svgElement = `#${cleanId}`;
    }
    
    // Add position
    config.position = [Math.round(comp.x), Math.round(comp.y)];
    
    // Clean up inputs/outputs - use clean IDs
    if (config.inputs) {
      config.inputs = config.inputs.map(id => this._cleanId(id));
    }
    if (config.outputs) {
      config.outputs = config.outputs.map(id => this._cleanId(id));
    }
    
    // Add iframe URL for valves
    if (comp.type === 'valve') {
      config.iframeUrl = '../../valve.html';
      config.modalTitle = `${comp.name} Control`;
    }
    
    // Add modal title for pumps
    if (comp.type === 'pump') {
      config.modalTitle = `${comp.name} Control`;
    }
    
    return config;
  }

  /**
   * Generate SVG for a component
   */
  _generateComponentSVG(comp) {
    const cleanId = this._cleanId(comp.id);
    const template = COMPONENT_LIBRARY[comp.key];
    
    if (comp.type === 'tank') {
      return `
        <!-- TANK: ${comp.name} -->
        <g id="${cleanId}" transform="translate(${comp.x}, ${comp.y})">
          <rect x="-80" y="-90" width="160" height="180" rx="12" fill="#0e1734" stroke="#2a3d78" stroke-width="3"></rect>
          <rect id="${cleanId}LevelRect" x="-74" y="88" width="148" height="0" fill="url(#liquid)" class="levelRect"></rect>
          <text x="0" y="-100" text-anchor="middle" fill="#9bb0ff" font-size="14">${comp.name}</text>
        </g>`;
    } else if (comp.type === 'valve') {
      // Apply the transform directly on the element with the id instead of an inner wrapper.
      return `
        <!-- VALVE: ${comp.name} -->
        <g id="${cleanId}" class="valve" transform="translate(${comp.x}, ${comp.y})" tabindex="0" role="button" aria-pressed="false" aria-label="${comp.name}">
          <image href="https://sco314.github.io/tank-sim/Valve-Icon-Transparent-bg.png" x="-38" y="-38" width="76" height="76" />
          <text x="0" y="-50" text-anchor="middle" fill="#9bb0ff" font-size="12">${comp.name}</text>
        </g>`;
    } else if (comp.type === 'pump') {
      return `
        <!-- PUMP: ${comp.name} -->
        <g id="${cleanId}" class="pump" transform="translate(${comp.x}, ${comp.y})" tabindex="0" role="button" aria-pressed="false" aria-label="${comp.name}">
          <image href="https://sco314.github.io/tank-sim/cent-pump-9-inlet-left.png" x="-60" y="-60" width="120" height="120" />
          <text x="0" y="-70" text-anchor="middle" fill="#9bb0ff" font-size="12">${comp.name}</text>
        </g>`;
    } else {
      // Generic component (feed, drain, sensor)
      return `
        <!-- ${comp.type.toUpperCase()}: ${comp.name} -->
        <g id="${cleanId}" transform="translate(${comp.x}, ${comp.y})">
          <circle r="20" fill="${template.color}20" stroke="${template.color}" stroke-width="2"></circle>
          <text x="0" y="5" text-anchor="middle" font-size="20">${template.icon}</text>
          <text x="0" y="-30" text-anchor="middle" fill="#9bb0ff" font-size="12">${comp.name}</text>
        </g>`;
    }
  }

  /**
   * Generate SVG for a pipe
   */
  _generatePipeSVG(conn, idx) {
    const fromComp = this.designer.components.get(conn.from);
    const toComp = this.designer.components.get(conn.to);
    
    // Simple straight line path
    const path = `M ${fromComp.x} ${fromComp.y} L ${toComp.x} ${toComp.y}`;
    
    // Use CSS classes for pipe styling instead of hard‑coded strokes. The engine's
    // stylesheet should define .pipe-body and .pipe-flow classes for width,
    // color and other styling. The id is maintained on the flow path for
    // animating flow within the pipe.
    return `
        <!-- PIPE: ${fromComp.name} to ${toComp.name} -->
        <g id="pipe${idx + 1}" class="pipe">
          <path class="pipe-body" d="${path}" fill="none"></path>
          <path id="pipe${idx + 1}Flow" class="pipe-flow" d="${path}" fill="none"></path>
        </g>`;
  }

  /**
   * Calculate distance between components
   */
  _calculateDistance(comp1, comp2) {
    const dx = comp2.x - comp1.x;
    const dy = comp2.y - comp1.y;
    return Math.round(Math.sqrt(dx * dx + dy * dy) / 100) / 10; // Convert pixels to meters
  }

  /**
   * Clean component ID for JavaScript variable names
   */
  _cleanId(id) {
    return id.replace(/[^a-zA-Z0-9]/g, '_');
  }

  /**
   * Download files
   */
  downloadFiles(files, simName) {
    // For now, download individually
    // In future, could use JSZip to create a zip file
    
    for (const [filename, content] of Object.entries(files)) {
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
    }
    
    alert(`✅ Exported 3 files for "${simName}"!\n\nPlace them in: sims/${simName}/`);
  }
}

// Export
window.SimulatorExporter = SimulatorExporter;
